### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by thesbros** [matthewwithanm/httpplease.js#15]
When using react-inlinesvg (which uses httpplease) in Electron (atom-shell), it uses node-XMLHttpRequest instead of the browser's. This causes it to break. Could it use a different method of checking if in a browser rather than the package.json browser field?

**Comment by matthewwithanm** [comment]
Hm…I really do feel like that's the ideal way to do it. What's actually consuming the package.json? I feel like maybe the really issue is to update that to identify the different parts of Electron correctly.

**Comment by thesbros** [comment]
Electron uses node's normal require. The browser field only affects browserify.

**Comment by matthewwithanm** [comment]
Sorry I wasn't clear; I know how the browser field works. Even though it started with browserify, it's become something of a de facto standard. I was a little vague because I wasn't sure if you were using a build tool or Electron directly but my gut reaction either way is that whatever's consuming the module (build tool or Electron itself) should be made aware of the browser field. This is kind of a weird case since Electron's browser isn't a regular browser, but I still think that makes the most sense. I'll open an issue on Electron to discuss. In the mean time, we can update [xhr.js][1] to use `window.XMLHttpRequest` if it exists.

[1]: https://github.com/matthewwithanm/httpplease.js/blob/master/lib/xhr.js

**Comment by thesbros** [comment]
Sounds good. Would you like me to submit a PR?

**Comment by matthewwithanm** [comment]
Sure!

**Comment by thesbros** [comment]
#16
